### ISSUE TITLE
Acronyme à ajouter

### ISSUE THREAD

**Issue by Jitrixis** [emmanuelgautier/supinfo-acronyms-list#2]
Obselete : STC (SUPINFO Training Center)
Service : SIUIS (SUPINFO International University Informations System)
Service : SMN (SUPINFO Management Network)
Service : SCO (SUPINFO Campus Organisation)
Service : SIIT (SUPINFO International Institute of Technology)
Exam : SMCE (SUPINFO Multiple Choice exam)
Exam : SGE ou TP (SUPINFO Graded Exercices ou Travaux Pratique)
Exam : SP ou SMP (SUPINFO Projects ou Mini projets)
PPT de Cours : CK (Core Knowledge)

Source : http://www.supinfo.com/fr/News98bfdcda-8c4c-4dd5-b8ca-ed673ba4662f.aspx + l'Azure AD du SIUIS

**Comment by emmanuelgautier** [comment]
Top :+1: Je vais rajouter ça.

**Comment by emmanuelgautier** [comment]
Fait !
https://github.com/emmanuelgautier/supinfo-acronyms-list/commit/60710d2bd3db67a9719f34b2250eb22471294ac0
